# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Pushes to another repository
        id: push_stats
        uses: le0pa/bolt-stats@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '/'
          destination-github-username: 'le0pa'
          destination-repository-name: 'boltdollar-front'
          user-email: <>
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: stats
